### ISSUE TITLE
Multiple binary variants for JDK 6/7/8

### ISSUE THREAD

**Issue by robfletcher** [robfletcher/strikt#41]

**Comment by Ray-Eldath** [comment]
Just about to propose a new issue for Java 1.6 support... Currently I'm transforming a library which is still using the somewhat legacy `assert` function called Ktorm, and the library is still targeting Java 1.6 for compability... so my refactor process can't go on due to the incosistency between the target platform of Strikt and Ktorm, which prohibit the usage of inline function e.g. `isA` and `expectThrows`. Really hope Strikt, as a fundamental assertion library, could target multiple versions soon.

I don't know whether there's some automation tool to simplify such transition, like automatically remove `inline` modifier cause it'll not affact the main logic...? If not then this will be a chore... Anyway, really appreciating your efforts of creating and maintaining such a convinent library! 😉

**Comment by robfletcher** [comment]
Kotlin 1.8 no longer supports JVM targets < 8 so I'm closing this.
